# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\nusersystem\"B\n\x11\x45nrollUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"G\n\x12\x45nrollUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\"\n\x11RequestOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"6\n\x12RequestOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x1a\x41uthenticateWithOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08otp_code\x18\x02 \x01(\t\"d\n\x1b\x41uthenticateWithOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nauth_token\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"(\n\x15GetUserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"-\n\x1cGetUserProfileByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"t\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1b\n\x13storage_quota_bytes\x18\x04 \x01(\x03\x12\x1a\n\x12storage_used_bytes\x18\x05 \x01(\x03\x32\xb9\x03\n\x0bUserService\x12K\n\nEnrollUser\x12\x1d.usersystem.EnrollUserRequest\x1a\x1e.usersystem.EnrollUserResponse\x12K\n\nRequestOTP\x12\x1d.usersystem.RequestOTPRequest\x1a\x1e.usersystem.RequestOTPResponse\x12\x66\n\x13\x41uthenticateWithOTP\x12&.usersystem.AuthenticateWithOTPRequest\x1a\'.usersystem.AuthenticateWithOTPResponse\x12L\n\x0eGetUserProfile\x12!.usersystem.GetUserProfileRequest\x1a\x17.usersystem.UserProfile\x12Z\n\x15GetUserProfileByEmail\x12(.usersystem.GetUserProfileByEmailRequest\x1a\x17.usersystem.UserProfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLUSERREQUEST']._serialized_start=26
  _globals['_ENROLLUSERREQUEST']._serialized_end=92
  _globals['_ENROLLUSERRESPONSE']._serialized_start=94
  _globals['_ENROLLUSERRESPONSE']._serialized_end=165
  _globals['_REQUESTOTPREQUEST']._serialized_start=167
  _globals['_REQUESTOTPREQUEST']._serialized_end=201
  _globals['_REQUESTOTPRESPONSE']._serialized_start=203
  _globals['_REQUESTOTPRESPONSE']._serialized_end=257
  _globals['_AUTHENTICATEWITHOTPREQUEST']._serialized_start=259
  _globals['_AUTHENTICATEWITHOTPREQUEST']._serialized_end=320
  _globals['_AUTHENTICATEWITHOTPRESPONSE']._serialized_start=322
  _globals['_AUTHENTICATEWITHOTPRESPONSE']._serialized_end=422
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=424
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=464
  _globals['_GETUSERPROFILEBYEMAILREQUEST']._serialized_start=466
  _globals['_GETUSERPROFILEBYEMAILREQUEST']._serialized_end=511
  _globals['_USERPROFILE']._serialized_start=513
  _globals['_USERPROFILE']._serialized_end=629
  _globals['_USERSERVICE']._serialized_start=632
  _globals['_USERSERVICE']._serialized_end=1073
# @@protoc_insertion_point(module_scope)
