# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """The User Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnrollUser = channel.unary_unary(
                '/usersystem.UserService/EnrollUser',
                request_serializer=user__pb2.EnrollUserRequest.SerializeToString,
                response_deserializer=user__pb2.EnrollUserResponse.FromString,
                _registered_method=True)
        self.RequestOTP = channel.unary_unary(
                '/usersystem.UserService/RequestOTP',
                request_serializer=user__pb2.RequestOTPRequest.SerializeToString,
                response_deserializer=user__pb2.RequestOTPResponse.FromString,
                _registered_method=True)
        self.AuthenticateWithOTP = channel.unary_unary(
                '/usersystem.UserService/AuthenticateWithOTP',
                request_serializer=user__pb2.AuthenticateWithOTPRequest.SerializeToString,
                response_deserializer=user__pb2.AuthenticateWithOTPResponse.FromString,
                _registered_method=True)
        self.GetUserProfile = channel.unary_unary(
                '/usersystem.UserService/GetUserProfile',
                request_serializer=user__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=user__pb2.UserProfile.FromString,
                _registered_method=True)
        self.GetUserProfileByEmail = channel.unary_unary(
                '/usersystem.UserService/GetUserProfileByEmail',
                request_serializer=user__pb2.GetUserProfileByEmailRequest.SerializeToString,
                response_deserializer=user__pb2.UserProfile.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """The User Service definition
    """

    def EnrollUser(self, request, context):
        """Method 1: Initial user enrollment with email and password
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestOTP(self, request, context):
        """Method 2: Generates an OTP and sends it to the user's email for login or password reset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateWithOTP(self, request, context):
        """Method 3: Authenticates a user using their email and the time-based OTP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """Method 4: Retrieves a user's basic profile and links to their storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfileByEmail(self, request, context):
        """Method 5: Get user profile by email (ADDED TO FIX YOUR ISSUE)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnrollUser': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollUser,
                    request_deserializer=user__pb2.EnrollUserRequest.FromString,
                    response_serializer=user__pb2.EnrollUserResponse.SerializeToString,
            ),
            'RequestOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestOTP,
                    request_deserializer=user__pb2.RequestOTPRequest.FromString,
                    response_serializer=user__pb2.RequestOTPResponse.SerializeToString,
            ),
            'AuthenticateWithOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateWithOTP,
                    request_deserializer=user__pb2.AuthenticateWithOTPRequest.FromString,
                    response_serializer=user__pb2.AuthenticateWithOTPResponse.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=user__pb2.GetUserProfileRequest.FromString,
                    response_serializer=user__pb2.UserProfile.SerializeToString,
            ),
            'GetUserProfileByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfileByEmail,
                    request_deserializer=user__pb2.GetUserProfileByEmailRequest.FromString,
                    response_serializer=user__pb2.UserProfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usersystem.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usersystem.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """The User Service definition
    """

    @staticmethod
    def EnrollUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersystem.UserService/EnrollUser',
            user__pb2.EnrollUserRequest.SerializeToString,
            user__pb2.EnrollUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersystem.UserService/RequestOTP',
            user__pb2.RequestOTPRequest.SerializeToString,
            user__pb2.RequestOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateWithOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersystem.UserService/AuthenticateWithOTP',
            user__pb2.AuthenticateWithOTPRequest.SerializeToString,
            user__pb2.AuthenticateWithOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersystem.UserService/GetUserProfile',
            user__pb2.GetUserProfileRequest.SerializeToString,
            user__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProfileByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersystem.UserService/GetUserProfileByEmail',
            user__pb2.GetUserProfileByEmailRequest.SerializeToString,
            user__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
